### ISSUE TITLE
container crashes on build

### ISSUE THREAD

**Issue by Buravchik** [oliverguenther/openproject-docker-dev#1]
`docker-compose up`
> Step 9/15 : RUN npm -g install bower
>  ---> Running in 7f9da83a1b80
> 
> /usr/lib/node_modules/npm/bin/npm-cli.js:85
>       let notifier = require('update-notifier')({pkg})
>           ^^^^^^^^
> SyntaxError: Unexpected identifier
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:945:3
> ERROR: Service 'web' failed to build: The command '/bin/sh -c npm -g install bower' returned a non-zero code: 8

**Comment by zombiesplat** [comment]
I am getting this too. initial GTS shows this is a problem with the node version. I'm investigating now that I see I'm not the only one with this problem and it has not been solved yet.
